name: "Check"
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    strategy:
      matrix:
        runner:
          - ubuntu-latest # x86_64-linux
          - ubuntu-24.04-arm # aarch64-linux
          - macos-15-intel # x86_64-darwin
          - macos-latest # aarch64-linux
    runs-on: ${{ matrix.runner }}
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Install nix
      uses: cachix/install-nix-action@master
      with:
        github_access_token: '${{ secrets.GITHUB_TOKEN }}'
    - name: Setup cachix
      uses: cachix/cachix-action@master
      with:
        name: linyinfeng
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Nix flake check
      run: nix flake check
